# Resolução Exercício 1 - Comparar Lista e Array

In [19]:
import numpy

array = numpy.arange(1000000)
lista = list(range(1000000))

In [20]:
%time for e in array: e2 = e * 2
%time for n in lista: n2 = n * 2

Wall time: 681 ms
Wall time: 166 ms


# Resolução Exercício 2 - Criar uma array de dez elementos e mudar os elementos nos índices 5 a 8 para 0

In [25]:
array2 = numpy.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array2[5:8] = 0
array2

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

# Resolução Exercício 3 - Criar uma matriz de três dimensões e imprimir a primeira dimensão.

In [29]:
array3d = numpy.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
(array3d[0]) # imprimir a primeira dimensao deste array de três dimensões

array([[0, 1, 2],
       [3, 4, 5]])

# Resolução Exercício 4 - Criar uma matriz e:

In [30]:
matriz1 = numpy.array([[0,1,2],[3,4,5],[6,7,8]])
matriz1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
matriz1[2] # imprimir a última linha

array([6, 7, 8])

In [44]:
matriz1[0:2,1:3] # imprimir os elementos da primeira e segunda linha, segunda e terceira coluna

array([[1, 2],
       [4, 5]])

# Resolução Exercício 5 - Criar uma matriz e calcular a sua transposta

In [48]:
# Módulo Reshape - pela uma lista de números e transforma em matriz, sendo que o primeiro argumento é linhas e o segundo colunas
matriz2 = numpy.arange(15).reshape(3,5) 
matriz2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
# Matriz Transposta - método T maiúsculo, com a letra minúscula não funciona
matriz2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Resolução Exercício 6 - Retorne o valor do array_a se o valor for True no array cond. Caso contrário, retorne o valor do array_b.

In [55]:
array_a = numpy.array([1.1, 1.2, 1.3, 1.4, 1.5])
array_b = numpy.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = numpy.array([True, False, True, True, False])

In [80]:
lista = []
for i, v in enumerate(cond): 
    if v == False:
        lista.append(array_b[i])
    else:    
        lista.append(array_a[i])
resposta = numpy.array(lista)
resposta

array([1.1, 2.2, 1.3, 1.4, 2.5])

# Resolução Exercício 7 - Criar um Array de dez elementos, salvar em disco no formato npy e carregar em um outro array

In [85]:
array3 = numpy.arange(10)
numpy.save('nome do arquivo.npy',array3) # comando para salvar algum array de números em disco
print(array3)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
array4 = numpy.load('nome do arquivo.npy') # comando para carregar algum array que esteja gravado em disco
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Resolução Exercício 8 - Retornar os valores únicos da série abaixo:

In [87]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [95]:
resposta = obj.unique()
print(resposta)

['c' 'a' 'd' 'b']


# Resolução Exercício 9 - Abrir o dataframe do endereço disposto abaixo:

In [98]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

import requests
site = requests.get(url)
site

<Response [200]>

In [108]:
data = site.json()

In [109]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    36403               BLD:CI try to fix arm64 build #36397   
1    36402                            BLD/CI: support for 3.9   
2    36401            TYP: alias IndexLabel without Optional    
3    36400           REF: implement putmask for CI/DTI/TDI/PI   
4    36398  Backport PR #36378: DOC: move release note for...   
5    36397                           BLD/CI: fix arm64 builds   
6    36396  Backport PR #36371 on branch 1.1.x (BUG: Fix M...   
7    36395  BUG: indexing with DataFrame with nullable boo...   
8    36394     CLN: remove unnecessary _convert_index_indexer   
9    36391  REF: share __getitem__ for Categorical/PandasA...   
10   36388    CLN: Made final changes to /pandas/tests/scalar   
11   36386  BLD: Restrict ci/code_checks.sh to tracked rep...   
12   36385  BUG: Always cast to Categorical in lexsort_ind...   
13   36384  REF: _is_compatible_with_other -> _can_union_w...   
14   36383  BUG: df.sort_values w/ key function fails with...   
15   36382                      ADMIN: Update stale PR action   
16   36380  ENH: Make non-aggregating methods on groupby g...   
17   36377  BUG: Weird behavior for comparison operations ...   
18   36375  BUG: MultiIndex.from_tuples() fails to infer d...   
19   36374  BUG: FooIndex.insert casting datetimelike NAs ...   
20   36373  REGR: inplace arithmetic operation on Series n...   
21   36372        REF: de-duplicate IntervalIndex compat code   
22   36369                           DOC: Enhance asfreq docs   
23   36368     CI: exclude directories from ci/code_checks.sh   
24   36365  BUG: Python Parser skipping over items if BOM ...   
25   36360            BUG: MutliIndex names lost during pivot   
26   36359  BUG: get_indexer methods return int64 instead ...   
27   36358  Fix documentation for new float_precision on r...   
28   36357                            Dispatch string methods   
29   36354  DEV: doctests fail on automatic int32/int64 se...   

                                               labels state  
0                                                  []  open  
1   [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
2   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
3                                                  []  open  
4   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
5   [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
6   [{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2...  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
9   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
10  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
11  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
12  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
13                                                 []  open  
14  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open  
15  [{'id': 32933285, 'node_id': 'MDU6TGFiZWwzMjkz...  open  
16  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19                                                 []  open  
20  [{'id': 2085877452, 'node_id': 'MDU6TGFiZWwyMD...  open  
21                                                 []  open  
22  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
23  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
24  [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
28  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
29  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open

# Exercício 10 - Repetir o exercício acima apenas com outro site

In [110]:
url2 = 'http://api.sidra.ibge.gov.br/values/t/793/g/2/v/all/p/all?formato=json'
reconhecer = requests.get(url2)

In [131]:
dados = reconhecer.json()
cabeçalho = dados[0]
cabeçalho

{'NC': 'Nível Territorial (Código)',
 'NN': 'Nível Territorial',
 'D1C': 'Brasil, Grande Região e UF (Código)',
 'D1N': 'Brasil, Grande Região e UF',
 'D2C': 'Variável (Código)',
 'D2N': 'Variável',
 'D3C': 'Ano (Código)',
 'D3N': 'Ano',
 'MC': 'Unidade de Medida (Código)',
 'MN': 'Unidade de Medida',
 'V': 'Valor'}

In [133]:
tabela = pd.DataFrame(dados[1:])
tabela

NC                    NN D1C                  D1N D2C                  D2N  \
0   1                Brasil   1               Brasil  93  População residente   
1   2         Grande Região   1                Norte  93  População residente   
2   3  Unidade da Federação  11             Rondônia  93  População residente   
3   3  Unidade da Federação  12                 Acre  93  População residente   
4   3  Unidade da Federação  13             Amazonas  93  População residente   
5   3  Unidade da Federação  14              Roraima  93  População residente   
6   3  Unidade da Federação  15                 Pará  93  População residente   
7   3  Unidade da Federação  16                Amapá  93  População residente   
8   3  Unidade da Federação  17            Tocantins  93  População residente   
9   2         Grande Região   2             Nordeste  93  População residente   
10  3  Unidade da Federação  21             Maranhão  93  População residente   
11  3  Unidade da Federação  22                Piauí  93  População residente   
12  3  Unidade da Federação  23                Ceará  93  População residente   
13  3  Unidade da Federação  24  Rio Grande do Norte  93  População residente   
14  3  Unidade da Federação  25              Paraíba  93  População residente   
15  3  Unidade da Federação  26           Pernambuco  93  População residente   
16  3  Unidade da Federação  27              Alagoas  93  População residente   
17  3  Unidade da Federação  28              Sergipe  93  População residente   
18  3  Unidade da Federação  29                Bahia  93  População residente   
19  2         Grande Região   3              Sudeste  93  População residente   
20  3  Unidade da Federação  31         Minas Gerais  93  População residente   
21  3  Unidade da Federação  32       Espírito Santo  93  População residente   
22  3  Unidade da Federação  33       Rio de Janeiro  93  População residente   
23  3  Unidade da Federação  35            São Paulo  93  População residente   
24  2         Grande Região   4                  Sul  93  População residente   
25  3  Unidade da Federação  41               Paraná  93  População residente   
26  3  Unidade da Federação  42       Santa Catarina  93  População residente   
27  3  Unidade da Federação  43    Rio Grande do Sul  93  População residente   
28  2         Grande Região   5         Centro-Oeste  93  População residente   
29  3  Unidade da Federação  50   Mato Grosso do Sul  93  População residente   
30  3  Unidade da Federação  51          Mato Grosso  93  População residente   
31  3  Unidade da Federação  52                Goiás  93  População residente   
32  3  Unidade da Federação  53     Distrito Federal  93  População residente   

     D3C   D3N  MC       MN          V  
0   2007  2007  45  Pessoas  183987291  
1   2007  2007  45  Pessoas   14623316  
2   2007  2007  45  Pessoas    1453756  
3   2007  2007  45  Pessoas     655385  
4   2007  2007  45  Pessoas    3221939  
5   2007  2007  45  Pessoas     395725  
6   2007  2007  45  Pessoas    7065573  
7   2007  2007  45  Pessoas     587311  
8   2007  2007  45  Pessoas    1243627  
9   2007  2007  45  Pessoas   51534406  
10  2007  2007  45  Pessoas    6118995  
11  2007  2007  45  Pessoas    3032421  
12  2007  2007  45  Pessoas    8185286  
13  2007  2007  45  Pessoas    3013740  
14  2007  2007  45  Pessoas    3641395  
15  2007  2007  45  Pessoas    8485386  
16  2007  2007  45  Pessoas    3037103  
17  2007  2007  45  Pessoas    1939426  
18  2007  2007  45  Pessoas   14080654  
19  2007  2007  45  Pessoas   77873120  
20  2007  2007  45  Pessoas   19273506  
21  2007  2007  45  Pessoas    3351669  
22  2007  2007  45  Pessoas   15420375  
23  2007  2007  45  Pessoas   39827570  
24  2007  2007  45  Pessoas   26733595  
25  2007  2007  45  Pessoas   10284503  
26  2007  2007  45  Pessoas    5866252  
27  2007  2007  45  Pessoas   10582840  
28  2007  2007  45  Pessoas   13222854  
29  2007  2007  45